### ISSUE TITLE
No data included contrary to stated in readme?

### ISSUE THREAD

**Issue by instagibbs** [benanne/kaggle-galaxies#1]
I can regenerate it, was just wondering.

edit: Oh, I just drop the kaggle files in, even if I'm using pre-processed data?

**Comment by benanne** [comment]
Indeed :) I only included a few utility files, not the raw training and testing data, as that is about 2GB in size.

**Comment by instagibbs** [comment]
thanks! This seems like a great way to verify my GPU/CUDA setup is finally working, and very helpful code for Theano. Torch7 stuff has been much more touchy.

Looks like my run will take 60 hours.
