### ISSUE TITLE
Help for running this code

### ISSUE THREAD

**Issue by nejyeah** [benanne/kaggle-galaxies#4]
Thanks for sharing your code and having done such an excellent work. 
I have install the dependencies and copy the data to RAM. But when I run:
      >  python  try_convnet_cc_multirotflip_3x69r45_maxout2048_extradense.py
the program stop and print the follows(the tail are Alex cuda-convnet code):

Using gpu device 0: GeForce GTS 450
Set up data loading
Preprocess validation data upfront
/usr/local/lib/python2.7/dist-packages/scikit_image-0.10.1-py2.7-linux-x86_64.egg/skimage/transform/_geometric.py:126: UserWarning: `_matrix` attribute is deprecated, use `params` instead.
  warnings.warn('`_matrix` attribute is deprecated, '
/usr/local/lib/python2.7/dist-packages/scikit_image-0.10.1-py2.7-linux-x86_64.egg/skimage/transform/_geometric.py:126: UserWarning: `_matrix` attribute is deprecated, use `params` instead.
  warnings.warn('`_matrix` attribute is deprecated, '
/usr/local/lib/python2.7/dist-packages/scikit_image-0.10.1-py2.7-linux-x86_64.egg/skimage/transform/_geometric.py:126: UserWarning: `_matrix` attribute is deprecated, use `params` instead.
  warnings.warn('`_matrix` attribute is deprecated, '
/usr/local/lib/python2.7/dist-packages/scikit_image-0.10.1-py2.7-linux-x86_64.egg/skimage/transform/_geometric.py:126: UserWarning: `_matrix` attribute is deprecated, use `params` instead.
  warnings.warn('`_matrix` attribute is deprecated, '
/usr/local/lib/python2.7/dist-packages/theano/sandbox/rng_mrg.py:768: UserWarning: MRG_RandomStreams Can't determine #streams from size (Shape.0), guessing 60*256
  nstreams = self.n_streams(size)
/usr/local/lib/python2.7/dist-packages/theano/tensor/subtensor.py:110: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  start in [None, 0] or
/usr/local/lib/python2.7/dist-packages/theano/tensor/subtensor.py:114: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  stop in [None, length, maxsize] or
/usr/local/lib/python2.7/dist-packages/theano/tensor/subtensor.py:190: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if stop in [None, maxsize]:
/home/gpu-server2/kaggle/pylearn2/pylearn2/sandbox/cuda_convnet/__init__.py:66: UserWarning: You are using probably a too old Theano version. That will cause compilation crash. If so, update Theano.
  "You are using probably a too old Theano version. That"
1 /*
2  \* Copyright (c) 2011, Alex Krizhevsky (akrizhevsky@gmail.com)
3  \* All rights reserved.
4  *
5  \* Redistribution and use in source and binary forms, with or without modification,
6  \* are permitted provided that the following conditions are met:
7  *
8  \* - Redistributions of source code must retain the above copyright notice,
9  \*   this list of conditions and the following disclaimer.

**Comment by nejyeah** [comment]
I have update the Theano, but get the same printings

**Comment by benanne** [comment]
You will want to install Theano from git. The 0.6.0 release is very old and some changes happened in both pylearn2 and Theano which means that they had to be updated simultaneously. So I guess that's what you're seeing. Try installing Theano from git, then it should work :)

**Comment by benanne** [comment]
Closing this, feel free to re-open the issue if updating Theano to the development version does not fix your problem.
