### ISSUE TITLE
When I run this program has encountered a problem,Can you help me？

### ISSUE THREAD

**Issue by lixunlove** [benanne/kaggle-galaxies#5]
@benanne  
Thanks for sharing your project code.
When I run this program I met the same problem as @nejyeah   ,but now I encountered another problem:
when I run:

> python try_convnet_cc_multirotflip_3x69r45_maxout2048_extradense.py

Using gpu device 0: GeForce GTX 650
Set up data loading
Preprocess validation data upfront
Error when tring to find the memory information on the GPU: initialization error
Error freeing device pointer 0x700e80000 (initialization error). Driver report 0 bytes free and 0 bytes total 
CudaNdarray_uninit: error freeing self->devdata. (self=0x7f3680676670, self->devata=0x700e80000)
Exception MemoryError: 'error freeing device pointer 0x700e80000 (initialization error)' in 'garbage collection' ignored
Fatal Python error: unexpected exception during garbage collection
Traceback (most recent call last):
  File "try_convnet_cc_multirotflip_3x69r45_maxout2048_extradense.py", line 135, in <module>
    xs_valid = [np.vstack(x_valid) for x_valid in xs_valid]
  File "/home/lixun/anaconda/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate

Thanks

**Comment by benanne** [comment]
That looks pretty bad - maybe you just don't have enough memory though. How much memory does your card have? You'll probably need at least 2GB to run the code.

**Comment by lixunlove** [comment]
Thank you for your reply .
My  card is  GeForce GTX 650   with  2GB memory  ,
Under what circumstances would cause “ValueError: need at least one array to concatenate”?

**Comment by benanne** [comment]
I think the problem is the 'initialization error', not the concatenation error. That's probably just a consequence of the previous error.

Another possibility is that it is unrelated and that the dataset could not be loaded. Did you download the JPEG files and extract them in the right locations?

**Comment by lixunlove** [comment]
Wether I copy the train and test images to /dev/shm by running python copy data to shm.py or modify the from_ram parameter to False  is the same error.
PS:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2014 NVIDIA Corporation
Built on Thu_Jul_17_21:41:27_CDT_2014
Cuda compilation tools, release 6.5, V6.5.12

**Comment by benanne** [comment]
Okay. Assuming both errors are related: try `export CUDA_LAUNCH_BLOCKING=1` and then running your code (see http://comments.gmane.org/gmane.comp.mathematics.theano.user/467 ). Maybe that will give you a better error message.

If that doesn't help, I would suggest asking on the Theano mailinglist as this is probably either an issue with Theano or a hardware issue, and not really a problem with this code.
